# Run Jekyll with `bundle exec`:
# bundle exec jekyll serve

source "https://rubygems.org"
# default theme for new Jekyll sites.
gem "minima", "~> 2.5"

# To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

gem "minimal-mistakes-jekyll"

gem "jekyll-include-cache"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

